### ISSUE TITLE
Missing information as to why Linux is not classified as Unix by the Open Group

### ISSUE THREAD

**Issue by voronoipotato** [sirredbeard/Awesome-UNIX#35]
Is it just a certification that you can pay for? What if any aspects are missing? It's unclear to the reader if the open group hasn't rubber stamped it or if it is radically different.

**Comment by sirredbeard** [comment]
Having an OS declared a 'UNIX' requires passing a [set of certifications](http://www.opengroup.org/certification/idx/unix.html) maintained by The Open Group.

OS vendors usually have a third party audit their OS for UNIX standards compliance using [official test suites](https://www.opengroup.org/openbrand/testing/dates.html) and then submit the results to the Open Group and pay a [license fee](https://www.opengroup.org/openbrand/Brandfees.htm).

Linux is not declared a UNIX because there is no one 'Linux', there are thousands of distributions, including both community and enterprise distributions. 

The cost of the compliance audit and license fee is prohibitive for community distributions, which starts at $25k USD.

A handful of enterprise Linux distribution vendors _have_ gone through the process of having their OS audited and certified as UNIX. These are listed here: https://github.com/sirredbeard/Awesome-UNIX#unix-certified-linux-based-operating-systems

Most other enterprise Linux distribution vendors have a 'UNIX compatible' mode or add-on which applies tweaks so that their Linux distribution would pass The Open Group compliance audit, but they do not have the third-party audit or pay the license fee:

![image](https://user-images.githubusercontent.com/33820650/150578107-561df385-eda4-48de-99f0-6a3d55994db3.png)
